# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 611)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(10, 10, 131, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.host_input = QtWidgets.QLineEdit(self.frame)
        self.host_input.setGeometry(QtCore.QRect(10, 10, 113, 20))
        self.host_input.setText("")
        self.host_input.setObjectName("host_input")
        self.user_input = QtWidgets.QLineEdit(self.frame)
        self.user_input.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.user_input.setObjectName("user_input")
        self.password_input = QtWidgets.QLineEdit(self.frame)
        self.password_input.setGeometry(QtCore.QRect(10, 70, 113, 20))
        self.password_input.setObjectName("password_input")
        self.database_input = QtWidgets.QLineEdit(self.frame)
        self.database_input.setGeometry(QtCore.QRect(10, 100, 113, 20))
        self.database_input.setObjectName("database_input")
        self.wrong_connect = QtWidgets.QLabel(self.frame)
        self.wrong_connect.setGeometry(QtCore.QRect(10, 160, 111, 31))
        self.wrong_connect.setObjectName("wrong_connect")
        self.Connect_button = QtWidgets.QPushButton(self.frame)
        self.Connect_button.setGeometry(QtCore.QRect(10, 130, 111, 23))
        self.Connect_button.setObjectName("Connect_button")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setEnabled(True)
        self.frame_2.setGeometry(QtCore.QRect(140, 10, 571, 541))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.table = QtWidgets.QTableView(self.frame_2)
        self.table.setGeometry(QtCore.QRect(10, 40, 551, 131))
        self.table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.table.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.table.setObjectName("table")
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.info_label = QtWidgets.QLabel(self.frame_2)
        self.info_label.setGeometry(QtCore.QRect(10, 10, 551, 21))
        self.info_label.setObjectName("info_label")
        self.grafic = QtWidgets.QGraphicsView(self.frame_2)
        self.grafic.setGeometry(QtCore.QRect(10, 180, 551, 351))
        self.grafic.setObjectName("grafic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 724, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.host_input.setPlaceholderText(_translate("MainWindow", "host:"))
        self.user_input.setPlaceholderText(_translate("MainWindow", "user:"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "password:"))
        self.database_input.setPlaceholderText(_translate("MainWindow", "database:"))
        self.wrong_connect.setText(_translate("MainWindow", "Wrong Conect!"))
        self.Connect_button.setText(_translate("MainWindow", "Connect"))
        self.info_label.setText(_translate("MainWindow", "info:"))
